[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npx @11ty/eleventy --serve"
  port = 8888
  targetPort = 8080

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
